// This file was generated by $CPP_ASSISTANT_ROOT/scripts/generate_makefile_from_cpp_assistant.sh.
// Edit it before it can be practically used.

/*
 * Copyright (c) 2016-2018, Wen Xiongchang <udc577 at 126 dot com>
 * All rights reserved.
 *
 * This software is provided 'as-is', without any express or implied
 * warranty. In no event will the authors be held liable for any
 * damages arising from the use of this software.
 *
 * Permission is granted to anyone to use this software for any
 * purpose, including commercial applications, and to alter it and
 * redistribute it freely, subject to the following restrictions:
 *
 * 1. The origin of this software must not be misrepresented; you must
 * not claim that you wrote the original software. If you use this
 * software in a product, an acknowledgment in the product documentation
 * would be appreciated but is not required.
 *
 * 2. Altered source versions must be plainly marked as such, and
 * must not be misrepresented as being the original software.
 *
 * 3. This notice may not be removed or altered from any source
 * distribution.
 */

// NOTE: The original author also uses (short/code) names listed below,
//       for convenience or for a certain purpose, at different places:
//       wenxiongchang, wxc, Damon Wen, udc577

/*
 * mutable_customization.h
 *
 *  Created on: 2016/12/29
 *      Author: wenxiongchang
 * Description: Definitions completely specified by user.
 */

#ifndef __MUTABLE_CUSTOMIZATION_H__
#define __MUTABLE_CUSTOMIZATION_H__

/*
 * TODO: Customized command line setting macros and other macros below,
 *     or just leave what they are like currently if these default values are fine to you.
 */

#define USAGE_TITLE                         "TCP测试程序"
#define USAGE_FORMAT                        "[选项 ...] [目标 ...]\n其中命令行选项说明如下："
#define HELP_DESC                           "显示此帮助内容。"
#define VERSION_DESC                        "显示版本信息。"
#define CONFIG_LOADING_DESC                 "指定启动时加载的配置文件。"
#define CONFIG_FILE_COUNT                   1
#define CONFIG_ASSIGN_EXPRESSION            "=<配置文件名称>"
#define DAEMON_DESC                         "程序以守护进程形式来运行。"
#define QUIET_MODE_DESC                     "程序以静默模式运行，（启动时）尽量少输出信息。"

#define PROTO_HEADER_EXTENSIONS_SIZE        0

typedef struct extra_config_t
{
    ; // TODO: Add your own configuration items here, or leave it empty if there is none.
}extra_config_t;

typedef struct extra_resource_t
{
    ; // TODO: Add your own resource items here, or leave it empty if there is none.
}extra_resource_t;

#endif /* __MUTABLE_CUSTOMIZATION_H__ */
