// This file was generated by $CPP_ASSISTANT_ROOT/scripts/generate_makefile_from_cpp_assistant.sh.
// Edit it before it can be practically used.

/*
 * Copyright (c) 2016-2018, Wen Xiongchang <udc577 at 126 dot com>
 * All rights reserved.
 *
 * This software is provided 'as-is', without any express or implied
 * warranty. In no event will the authors be held liable for any
 * damages arising from the use of this software.
 *
 * Permission is granted to anyone to use this software for any
 * purpose, including commercial applications, and to alter it and
 * redistribute it freely, subject to the following restrictions:
 *
 * 1. The origin of this software must not be misrepresented; you must
 * not claim that you wrote the original software. If you use this
 * software in a product, an acknowledgment in the product documentation
 * would be appreciated but is not required.
 *
 * 2. Altered source versions must be plainly marked as such, and
 * must not be misrepresented as being the original software.
 *
 * 3. This notice may not be removed or altered from any source
 * distribution.
 */

// NOTE: The original author also uses (short/code) names listed below,
//       for convenience or for a certain purpose, at different places:
//       wenxiongchang, wxc, Damon Wen, udc577

/*
 * mutable_customization.h
 *
 *  Created on: 2016/12/29
 *      Author: wenxiongchang
 * Description: Definitions completely specified by user.
 */

#ifndef __MUTABLE_CUSTOMIZATION_H__
#define __MUTABLE_CUSTOMIZATION_H__

typedef struct extra_config_t
{
    ; // TODO: Add your own configuration items here, or leave it empty if there is none.
}extra_config_t;

typedef struct extra_resource_t
{
    ; // TODO: Add your own resource items here, or leave it empty if there is none.
}extra_resource_t;

#endif /* __MUTABLE_CUSTOMIZATION_H__ */
