#!/bin/bash

TEMPLATE_ROOT=$(dirname $0)/../code/frameworks/customization_templates
PROJECTS=(`ls $TEMPLATE_ROOT`)
PROJECT_COUNT=${#PROJECTS[*]}

echo "Select the project:"
for i in `seq 0 $(($PROJECT_COUNT - 1))`
do
	echo "    ${i}. ${PROJECTS[$i]}"
done

read -p "Please enter the number [will choose 0 if pressing Enter directly]: " project_num

if [ -z "$project_num" ]
then
	project_num=0
elif [[ $project_num == *[!0-9]* ]]
then
	echo "**** Enter a number, please!"
	exit 1
elif [ $project_num -ge $PROJECT_COUNT ]
then
	echo "**** Invalid number, will abort!"
	exit 1
fi

project=${PROJECTS[$project_num]}

echo "Enter the directory where the generated project will be put."
read -p "Please enter the directory [will be \".\" if pressing Enter directly]: " target_dir

if [ -z "$target_dir" ]
then
	target_dir=.
fi

if [ ! -d "$target_dir" ]
then
	echo "**** Directory does not exist: $target_dir"
	exit 1
fi

printf "Create project root directory [%s] first, or copy project contents directly?\n" $project
echo "    0. Copy project contents directly"
echo "    1. Create project root first"
printf "Please choose [will choose 0 if pressing Enter directly]: "
read create_flag

if [ -z "$create_flag" ] || [ "$create_flag" = "0" ]
then
	printf ""
else
	target_dir=$target_dir/$project
	mkdir -p $target_dir
	echo "mkdir -p $target_dir"
fi

echo "$TEMPLATE_ROOT/$project/* --> $target_dir/"
echo "Copying project contents ..."
find $TEMPLATE_ROOT/$project/ -type f
cp -r $TEMPLATE_ROOT/$project/* $target_dir/

if [ "$project" = "simple_app" ]
then
	project_absolute_path=$(cd $target_dir && pwd)
	target_name=$(basename $project_absolute_path)
	if [ "$target_name" != "." ] && [ "$target_name" != ".." ] && [ "$target_name" != "/" ]
	then
		sed -i "/^TARGET := .*/s//TARGET := $target_name/g" $target_dir/Makefile
	fi
fi

echo "#" > $target_dir/README.txt
echo "# Contents in this directory were generated by \$CPP_ASSISTANT_ROOT/scripts/$(basename $0) on $(date +%Y/%m/%d)." >> $target_dir/README.txt
echo "# Edit the customized parts and add your own stuff before they can be used." >> $target_dir/README.txt
echo "# For more help, see documents in directory \$CPP_ASSISTANT_ROOT/docs." >> $target_dir/README.txt
echo "#" >> $target_dir/README.txt

echo "Generation done: $target_dir"

