DEFINES += -D_REENTRANT -DCA_NEWEST_MOD_DATE=\"$(CA_MOD_DATE)\" -DCA_NEWEST_MAIN_VER=\"$(CA_MAIN_VER)\"
ifneq ($(CA_SVN_VER),)
	DEFINES += -DCA_SVN_VER=\"$(CA_SVN_VER)\"
endif
ifeq ($(CA_USE_STL),0)
	DEFINES += -UCA_USE_STL
	STL_FLAG = "CA_USE_STL=0"
else
	DEFINES += -DCA_USE_STL=1
	STL_FLAG = "CA_USE_STL=1"
endif
ifeq ($(DEBUG), 1)
	DEBUG_FLAG = "DEBUG=1"
	DEFINES += -DDEBUG
	OPTIMIZE_FLAG = -O0
else
	DEBUG_FLAG =
	OPTIMIZE_FLAG = -O2
endif
CFLAGS += $(DEFINES) $(INCLUDES) $(OPTIMIZE_FLAG) -g -fPIC
CXXFLAGS = $(CFLAGS) -ftemplate-depth-128
LDFLAGS +=
